<a href="https://colab.research.google.com/github/Vijay7542/Machine-Learning-Projects/blob/master/Copy_of_Insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
path = kagglehub.dataset_download('mirichoi0218/insurance')

print(f'Data source import complete: {path}')


Using Colab cache for faster access to the 'insurance' dataset.
Data source import complete: /kaggle/input/insurance


In [3]:
import os

os.listdir("/kaggle/input/insurance")

['insurance.csv']

In [4]:
import pandas as pd

df=pd.read_csv(os.path.join(path,"insurance.csv"))

In [5]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [6]:
df["sex"]=df["sex"].replace({"male":0,"female":1})

/tmp/ipython-input-3903829483.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["sex"]=df["sex"].replace({"male":0,"female":1})


In [7]:
df.head()

age  sex     bmi  children smoker     region      charges
0   19    1  27.900         0    yes  southwest  16884.92400
1   18    0  33.770         1     no  southeast   1725.55230
2   28    0  33.000         3     no  southeast   4449.46200
3   33    0  22.705         0     no  northwest  21984.47061
4   32    0  28.880         0     no  northwest   3866.85520

In [8]:
import matplotlib.pyplot as plt

df["region"].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [9]:
df["smoker"]=df["smoker"].replace({"yes":0,"no":1})
df["region"]=df["region"].map({"southeast":0,"southwest":1,"northwest":2,"northeast":3})

/tmp/ipython-input-529095475.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["smoker"]=df["smoker"].replace({"yes":0,"no":1})


In [10]:
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    1  27.900         0       0       1  16884.92400
1   18    0  33.770         1       1       0   1725.55230
2   28    0  33.000         3       1       0   4449.46200
3   33    0  22.705         0       1       2  21984.47061
4   32    0  28.880         0       1       2   3866.85520

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   int64  
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   int64  
 5   region    1338 non-null   int64  
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(5)
memory usage: 73.3 KB


In [12]:
X=df.drop(columns=["charges"])
y=df.charges

In [13]:
print(X)

      age  sex     bmi  children  smoker  region
0      19    1  27.900         0       0       1
1      18    0  33.770         1       1       0
2      28    0  33.000         3       1       0
3      33    0  22.705         0       1       2
4      32    0  28.880         0       1       2
...   ...  ...     ...       ...     ...     ...
1333   50    0  30.970         3       1       2
1334   18    1  31.920         0       1       3
1335   18    1  36.850         0       1       0
1336   21    1  25.800         0       1       1
1337   61    1  29.070         0       0       2

[1338 rows x 6 columns]


In [14]:
print(y)

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64


In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)





In [16]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [17]:
print(X_train)

[[-1.08716652 -0.99106682 -1.14087456 -0.91749963  0.50839872  0.45531212]
 [-0.80210593  1.0090137  -0.66584152  0.7436053   0.50839872 -1.32164531]
 [ 0.83699246 -0.99106682  1.52879447 -0.08694717  0.50839872 -0.43316659]
 ...
 [ 1.33584849 -0.99106682 -0.8879673  -0.91749963  0.50839872  1.34379084]
 [-0.1607196   1.0090137   2.84324666  0.7436053  -1.9669601  -0.43316659]
 [ 1.12205304 -0.99106682 -0.10179179 -0.91749963  0.50839872 -0.43316659]]


In [18]:
print(y_train)

693      2352.96845
1297     4340.44090
634      9391.34600
1022    42211.13820
178      8823.27900
           ...     
1095     4561.18850
1130     8582.30230
1294    11931.12525
860     46113.51100
1126    10214.63600
Name: charges, Length: 1003, dtype: float64


In [19]:
print(y_test)

764      9095.06825
887      5272.17580
890     29330.98315
1293     9301.89355
259     33750.29180
           ...     
342     13217.09450
308     11944.59435
1128    14358.36437
503     32548.34050
1197     5699.83750
Name: charges, Length: 335, dtype: float64


In [20]:
print(X_test)

[[ 0.40940157  1.0090137  -0.8879673   0.7436053   0.50839872  1.34379084]
 [-0.23198475  1.0090137  -0.08182542 -0.91749963  0.50839872  0.45531212]
 [ 1.76343937  1.0090137  -0.60344664 -0.91749963 -1.9669601   0.45531212]
 ...
 [-0.37451505 -0.99106682  0.38072864 -0.08694717  0.50839872 -0.43316659]
 [-1.44349225 -0.99106682 -0.04355656 -0.91749963 -1.9669601  -1.32164531]
 [ 0.12434098 -0.99106682  0.5055184  -0.91749963  0.50839872 -1.32164531]]


In [21]:
print(X_train.ndim,X_test.ndim,y_train.ndim,y_test.ndim)

2 2 1 1


In [22]:
import torch
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train.values,dtype=torch.float32).view(-1,1)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.float32).view(-1,1)

In [23]:
print(y_train_tensor)

tensor([[ 2352.9685],
        [ 4340.4409],
        [ 9391.3457],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])


In [24]:
print(y_test_tensor)

tensor([[ 9095.0684],
        [ 5272.1758],
        [29330.9824],
        [ 9301.8936],
        [33750.2930],
        [ 4536.2588],
        [ 2117.3389],
        [14210.5361],
        [ 3732.6250],
        [10264.4424],
        [18259.2168],
        [ 7256.7231],
        [ 3947.4131],
        [46151.1250],
        [48673.5586],
        [44202.6523],
        [ 9800.8887],
        [42969.8516],
        [ 8233.0977],
        [21774.3223],
        [ 5080.0962],
        [ 7441.5010],
        [ 1256.2990],
        [ 2755.0210],
        [11085.5869],
        [10923.9336],
        [12644.5889],
        [18804.7520],
        [ 9715.8408],
        [ 1131.5066],
        [15828.8213],
        [11842.6240],
        [ 2020.5522],
        [ 5693.4307],
        [ 2904.0879],
        [ 7448.4038],
        [ 2597.7791],
        [ 7337.7480],
        [23887.6621],
        [38709.1758],
        [ 4687.7969],
        [ 2643.2686],
        [11674.1299],
        [12124.9922],
        [ 4889.9995],
        [1

In [25]:
print(y_train_tensor)
print(y_train_tensor.shape)

tensor([[ 2352.9685],
        [ 4340.4409],
        [ 9391.3457],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])
torch.Size([1003, 1])


In [26]:
print(X_train_tensor)
print(X_train_tensor.shape)

tensor([[-1.0872, -0.9911, -1.1409, -0.9175,  0.5084,  0.4553],
        [-0.8021,  1.0090, -0.6658,  0.7436,  0.5084, -1.3216],
        [ 0.8370, -0.9911,  1.5288, -0.0869,  0.5084, -0.4332],
        ...,
        [ 1.3358, -0.9911, -0.8880, -0.9175,  0.5084,  1.3438],
        [-0.1607,  1.0090,  2.8432,  0.7436, -1.9670, -0.4332],
        [ 1.1221, -0.9911, -0.1018, -0.9175,  0.5084, -0.4332]])
torch.Size([1003, 6])


In [27]:
print(y_test_tensor)
print(y_test_tensor.shape)

tensor([[ 9095.0684],
        [ 5272.1758],
        [29330.9824],
        [ 9301.8936],
        [33750.2930],
        [ 4536.2588],
        [ 2117.3389],
        [14210.5361],
        [ 3732.6250],
        [10264.4424],
        [18259.2168],
        [ 7256.7231],
        [ 3947.4131],
        [46151.1250],
        [48673.5586],
        [44202.6523],
        [ 9800.8887],
        [42969.8516],
        [ 8233.0977],
        [21774.3223],
        [ 5080.0962],
        [ 7441.5010],
        [ 1256.2990],
        [ 2755.0210],
        [11085.5869],
        [10923.9336],
        [12644.5889],
        [18804.7520],
        [ 9715.8408],
        [ 1131.5066],
        [15828.8213],
        [11842.6240],
        [ 2020.5522],
        [ 5693.4307],
        [ 2904.0879],
        [ 7448.4038],
        [ 2597.7791],
        [ 7337.7480],
        [23887.6621],
        [38709.1758],
        [ 4687.7969],
        [ 2643.2686],
        [11674.1299],
        [12124.9922],
        [ 4889.9995],
        [1

In [28]:
print(X_test_tensor)
print(X_test_tensor.shape)

tensor([[ 0.4094,  1.0090, -0.8880,  0.7436,  0.5084,  1.3438],
        [-0.2320,  1.0090, -0.0818, -0.9175,  0.5084,  0.4553],
        [ 1.7634,  1.0090, -0.6034, -0.9175, -1.9670,  0.4553],
        ...,
        [-0.3745, -0.9911,  0.3807, -0.0869,  0.5084, -0.4332],
        [-1.4435, -0.9911, -0.0436, -0.9175, -1.9670, -1.3216],
        [ 0.1243, -0.9911,  0.5055, -0.9175,  0.5084, -1.3216]])
torch.Size([335, 6])


In [29]:
import torch
import torch.nn as nn
import torch.optim as optim

class simpleNN(nn.Module):
  def __init__(self,input_size):
    super(simpleNN,self).__init__()
    self.fc1=nn.Linear(input_size,64)
    self.relu1=nn.ReLU()
    self.fc2=nn.Linear(64,128)
    self.relu2=nn.ReLU()
    self.fc3=nn.Linear(128,256)
    self.relu3=nn.ReLU()
    self.fc4=nn.Linear(256,1)
  def forward(self,x):
    x=self.fc1(x)
    x=self.relu1(x)
    x=self.fc2(x)
    x=self.relu2(x)
    x=self.fc3(x)
    x=self.relu3(x)
    x=self.fc4(x)
    return x

In [30]:
model_func=simpleNN(input_size=6)

In [31]:
model_func

simpleNN(
  (fc1): Linear(in_features=6, out_features=64, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=64, out_features=128, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=128, out_features=256, bias=True)
  (relu3): ReLU()
  (fc4): Linear(in_features=256, out_features=1, bias=True)
)

In [32]:
loss_fn=nn.MSELoss()
optimizer=optim.Adam(model_func.parameters(),lr=0.001)

In [33]:
  epoch=1000

  for e in range(epoch):
    model_func.train()
    optimizer.zero_grad()
    predictions=model_func(X_train_tensor)
    loss=loss_fn(predictions,y_train_tensor)
    loss.backward()
    optimizer.step()

    if (e+1)%50==0:
      print(f" The epoch [{e+1}/{epoch}] having loss {loss.item():.4f}")

 The epoch [50/1000] having loss 317974208.0000
 The epoch [100/1000] having loss 263664656.0000
 The epoch [150/1000] having loss 98391264.0000
 The epoch [200/1000] having loss 50405788.0000
 The epoch [250/1000] having loss 37465212.0000
 The epoch [300/1000] having loss 33422716.0000
 The epoch [350/1000] having loss 31895432.0000
 The epoch [400/1000] having loss 30909354.0000
 The epoch [450/1000] having loss 30068508.0000
 The epoch [500/1000] having loss 29302016.0000
 The epoch [550/1000] having loss 28588054.0000
 The epoch [600/1000] having loss 27941606.0000
 The epoch [650/1000] having loss 27335850.0000
 The epoch [700/1000] having loss 26770108.0000
 The epoch [750/1000] having loss 26251546.0000
 The epoch [800/1000] having loss 25764020.0000
 The epoch [850/1000] having loss 25301152.0000
 The epoch [900/1000] having loss 24861172.0000
 The epoch [950/1000] having loss 24445322.0000
 The epoch [1000/1000] having loss 24056904.0000


In [34]:
model_func.eval()
y_pred=model_func(X_test_tensor).detach().numpy()
y_pred

array([[10395.12  ],
       [ 5480.1045],
       [34692.36  ],
       [ 9778.172 ],
       [28197.7   ],
       [ 8300.5205],
       [ 3551.028 ],
       [15587.087 ],
       [ 6408.1   ],
       [10878.581 ],
       [21779.125 ],
       [ 7473.2847],
       [ 4576.8784],
       [49012.74  ],
       [50540.9   ],
       [45006.676 ],
       [12779.066 ],
       [41233.844 ],
       [ 9686.338 ],
       [28015.805 ],
       [ 6575.555 ],
       [ 7661.9214],
       [ 1421.7296],
       [ 6950.038 ],
       [11876.455 ],
       [12598.147 ],
       [13422.896 ],
       [ 6893.394 ],
       [11027.177 ],
       [ 1918.0162],
       [ 9259.691 ],
       [12496.862 ],
       [ 2003.9122],
       [ 7546.8677],
       [ 2648.2935],
       [10707.563 ],
       [ 3443.8914],
       [ 7758.52  ],
       [27452.654 ],
       [37102.383 ],
       [ 6732.3345],
       [ 2824.2227],
       [12644.449 ],
       [13214.194 ],
       [ 5414.0845],
       [13549.366 ],
       [ 5251.478 ],
       [ 5376

In [35]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
mse=mean_squared_error(y_pred,y_test_tensor.numpy())
rmse=np.sqrt(mse)
mae=mean_absolute_error(y_pred,y_test_tensor.numpy())
r2_score=r2_score(y_pred,y_test_tensor.numpy())

print("mse",mse)
print("rmse",rmse)
print("mae",mae)
print("r2_score",r2_score)



mse 23365140.0
rmse 4833.750096974398
mae 2907.308349609375
r2_score 0.8238157033920288


In [36]:
from sklearn.preprocessing import OneHotEncoder
import kagglehub

encoder=OneHotEncoder()

path=kagglehub.dataset_download("mirichoi0218/insurance")

print("Dataset path:",path)

Using Colab cache for faster access to the 'insurance' dataset.
Dataset path: /kaggle/input/insurance


In [37]:
import os
print(os.listdir("/kaggle/input/insurance"))

['insurance.csv']


In [38]:
import pandas as pd

df=pd.read_csv(os.path.join(path,"insurance.csv"))

In [39]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [40]:
encoded=encoder.fit_transform(df[["sex"]]).toarray()

In [41]:
df1=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
df1

sex_female  sex_male
0            1.0       0.0
1            0.0       1.0
2            0.0       1.0
3            0.0       1.0
4            0.0       1.0
...          ...       ...
1333         0.0       1.0
1334         1.0       0.0
1335         1.0       0.0
1336         1.0       0.0
1337         1.0       0.0

[1338 rows x 2 columns]

In [42]:
df=pd.concat([df,df1],axis=1)
df.head()

age     sex     bmi  children smoker     region      charges  sex_female  \
0   19  female  27.900         0    yes  southwest  16884.92400         1.0   
1   18    male  33.770         1     no  southeast   1725.55230         0.0   
2   28    male  33.000         3     no  southeast   4449.46200         0.0   
3   33    male  22.705         0     no  northwest  21984.47061         0.0   
4   32    male  28.880         0     no  northwest   3866.85520         0.0   

   sex_male  
0       0.0  
1       1.0  
2       1.0  
3       1.0  
4       1.0

In [43]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()
encoded=encoder.fit_transform(df["smoker"])


In [44]:
df2=pd.DataFrame(encoded,columns=["smoker"])
df2

smoker
0          1
1          0
2          0
3          0
4          0
...      ...
1333       0
1334       0
1335       0
1336       0
1337       1

[1338 rows x 1 columns]

In [45]:


df=pd.concat([df,df2],axis=1)

In [46]:
from sklearn.preprocessing import OrdinalEncoder

encoder=OrdinalEncoder(categories=[["southwest","southeast","northwest","northeast"]])

In [47]:
df.head()

age     sex     bmi  children  smoker     region      charges  sex_female  \
0   19  female  27.900         0     yes  southwest  16884.92400         1.0   
1   18    male  33.770         1      no  southeast   1725.55230         0.0   
2   28    male  33.000         3      no  southeast   4449.46200         0.0   
3   33    male  22.705         0      no  northwest  21984.47061         0.0   
4   32    male  28.880         0      no  northwest   3866.85520         0.0   

   sex_male  smoker  
0       0.0       1  
1       1.0       0  
2       1.0       0  
3       1.0       0  
4       1.0       0

In [48]:
encoded=encoder.fit_transform(df[["region"]])

In [49]:
pd.DataFrame(encoded,columns=["region_en"])

region_en
0           0.0
1           1.0
2           1.0
3           2.0
4           2.0
...         ...
1333        2.0
1334        3.0
1335        1.0
1336        0.0
1337        2.0

[1338 rows x 1 columns]

In [50]:
df.drop(columns=["smoker"],axis=1)

age     sex     bmi  children     region      charges  sex_female  \
0      19  female  27.900         0  southwest  16884.92400         1.0   
1      18    male  33.770         1  southeast   1725.55230         0.0   
2      28    male  33.000         3  southeast   4449.46200         0.0   
3      33    male  22.705         0  northwest  21984.47061         0.0   
4      32    male  28.880         0  northwest   3866.85520         0.0   
...   ...     ...     ...       ...        ...          ...         ...   
1333   50    male  30.970         3  northwest  10600.54830         0.0   
1334   18  female  31.920         0  northeast   2205.98080         1.0   
1335   18  female  36.850         0  southeast   1629.83350         1.0   
1336   21  female  25.800         0  southwest   2007.94500         1.0   
1337   61  female  29.070         0  northwest  29141.36030         1.0   

      sex_male  
0          0.0  
1          1.0  
2          1.0  
3          1.0  
4          1.0  
...        ...  
1333       1.0  
1334       0.0  
1335       0.0  
1336       0.0  
1337       0.0  

[1338 rows x 8 columns]

In [51]:
!pip install streamlit pyngrok


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 61.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 101.4 MB/s eta 0:00:00


In [52]:
from pyngrok import ngrok

ngrok.set_auth_token("YOUR_NGROK_AUTH_TOKEN")


In [53]:
%%writefile README.MD

Writing README.MD


In [54]:
%%writefile app.py
import streamlit as st

st.title("Streamlit from Google Colab")
st.write("Yes! Streamlit is running from Colab.")


Writing app.py


In [55]:
from google.colab import files
uploaded = files.upload()


KeyboardInterrupt: 

In [ ]:
%%writefile README.md


![My Image](Deep Learning.png)





In [ ]:
!cat README.md


In [ ]:
from IPython.display import Markdown

with open("README.md", "r") as f:
    display(Markdown(f.read()))


In [ ]:
import os

os.path.exists("Deep Learning.png")


In [58]:
import pandas as pd

df=pd.read_csv("Churn_Modelling.csv")

In [59]:
df.drop(columns=["RowNumber","CustomerId","Surname"],axis=1,inplace=True)

In [60]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [ ]:
df.head()

In [61]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [62]:
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder

one_hot_encoder=OneHotEncoder()
encoded_geography=one_hot_encoder.fit_transform(df[["Geography"]]).toarray()
df1=pd.DataFrame(encoded_geography,columns=one_hot_encoder.get_feature_names_out())


In [63]:
df=pd.concat([df,df1],axis=1)

In [ ]:
df.head()

In [64]:
Label_encoder=LabelEncoder()
encoded_gender=Label_encoder.fit_transform(df["Gender"])
df2=pd.DataFrame(encoded_gender,columns=["Gender_en"])

In [65]:
df2.Gender_en.value_counts()

Gender_en
1    5457
0    4543
Name: count, dtype: int64

In [66]:
df=pd.concat([df,df2],axis=1)

In [67]:
df.drop(["Geography","Gender"],axis=1,inplace=True)

In [68]:
X=df.drop("Exited",axis=1)
y=df["Exited"]

In [69]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)


In [70]:
print(X_train)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
9254          686   32       6       0.00              2          1   
1561          632   42       4  119624.60              2          1   
1670          559   24       3  114739.92              1          1   
6087          561   27       9  135637.00              1          1   
6669          517   56       9  142147.32              1          0   
...           ...  ...     ...        ...            ...        ...   
5734          768   54       8   69712.74              1          1   
5191          682   58       1       0.00              1          1   
5390          735   38       1       0.00              3          0   
860           667   43       8  190227.46              1          1   
7270          697   51       1  147910.30              1          1   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
9254               1        179093.26               1.0              

In [71]:
print("Samples for training",X_train.shape[0])
print("Sample for testing",X_test.shape[0])

Samples for training 8000
Sample for testing 2000


In [72]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [73]:
print(X_train)

[[ 0.35649971 -0.6557859   0.34567966 ... -0.57946723 -0.57638802
   0.91324755]
 [-0.20389777  0.29493847 -0.3483691  ...  1.72572313 -0.57638802
   0.91324755]
 [-0.96147213 -1.41636539 -0.69539349 ... -0.57946723  1.73494238
   0.91324755]
 ...
 [ 0.86500853 -0.08535128 -1.38944225 ... -0.57946723 -0.57638802
  -1.09499335]
 [ 0.15932282  0.3900109   1.03972843 ... -0.57946723 -0.57638802
   0.91324755]
 [ 0.47065475  1.15059039 -1.38944225 ...  1.72572313 -0.57638802
   0.91324755]]


In [74]:
import torch
import torch.nn as nn
import torch.optim as optim

class ChurnANN(nn.Module):
  def __init__(self,input_size):
    super(ChurnANN,self).__init__()
    self.fc1=nn.Linear(input_size,32)
    self.relu1=nn.ReLU()
    self.fc2=nn.Linear(32,16)
    self.relu2=nn.ReLU()
    self.fc3=nn.Linear(16,8)
    self.relu3=nn.ReLU()
    self.output=nn.Linear(8,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,x):
    x=self.relu1(self.fc1(x))
    x=self.relu2(self.fc2(x))
    x=self.relu3(self.fc3(x))
    x=self.sigmoid(self.output(x))
    return x

In [75]:
model=ChurnANN(input_size=12)

In [76]:
print(model)

ChurnANN(
  (fc1): Linear(in_features=12, out_features=32, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=32, out_features=16, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=16, out_features=8, bias=True)
  (relu3): ReLU()
  (output): Linear(in_features=8, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [77]:
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train.values,dtype=torch.float32).view(-1,1)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.float32).view(-1,1)

In [78]:
print(y_train_tensor)

tensor([[0.],
        [0.],
        [1.],
        ...,
        [1.],
        [1.],
        [0.]])


In [79]:
loss_fn=nn.BCELoss()
optimizer=optim.Adam(model.parameters(),lr=0.001)

In [80]:
print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)


In [81]:
epoch=1000

for e in range(epoch):
  model.train()
  optimizer.zero_grad()
  prediction=model(X_train_tensor)
  loss=loss_fn(prediction,y_train_tensor)
  loss.backward()
  optimizer.step()
  if (e+1)%50==0:
    print(f"for batch [{e+1}/{epoch}] has loss {loss.item():.4f}")


for batch [50/1000] has loss 0.6015
for batch [100/1000] has loss 0.4694
for batch [150/1000] has loss 0.4383
for batch [200/1000] has loss 0.4105
for batch [250/1000] has loss 0.3718
for batch [300/1000] has loss 0.3410
for batch [350/1000] has loss 0.3289
for batch [400/1000] has loss 0.3236
for batch [450/1000] has loss 0.3190
for batch [500/1000] has loss 0.3147
for batch [550/1000] has loss 0.3104
for batch [600/1000] has loss 0.3063
for batch [650/1000] has loss 0.3026
for batch [700/1000] has loss 0.2984
for batch [750/1000] has loss 0.2944
for batch [800/1000] has loss 0.2908
for batch [850/1000] has loss 0.2872
for batch [900/1000] has loss 0.2830
for batch [950/1000] has loss 0.2790
for batch [1000/1000] has loss 0.2759


In [82]:
model.eval()
with torch.no_grad():
    preds=model(X_test_tensor)
    preds = (preds >= 0.5).float()

y_true=y_test_tensor.numpy()
print(y_true)
y_pred=preds.numpy()
print(y_pred)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy:", accuracy_score(y_true, y_pred))
print("Precision:", precision_score(y_true, y_pred))
print("Recall:", recall_score(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))


[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]
Accuracy: 0.8515
Precision: 0.6643835616438356
Recall: 0.49363867684478374
F1 Score: 0.5664233576642336
Confusion Matrix:
 [[1509   98]
 [ 199  194]]


In [84]:
from sklearn.model_selection import GridSearchCV
param_grid={"neurons":[16,32,64,128],"layers":[1,2,3],"epochs":[50,100]}
grid=GridSearchCV(estimator=model,param_grid=param_grid,n_jobs=-1,cv=3,verbose=1)
grid_result=grid.fit(X_train,y_train)
print(grid_result.best_score_,grid_result.best_params_)


TypeError: GridSearchCV.__init__() missing 1 required positional argument: 'estimator'

In [87]:
from skorch import NeuralNetClassifier

net = NeuralNetClassifier(
    ChurnANN,
    max_epochs=10,
    lr=0.001,
    batch_size=32,
)




In [88]:
param_grid = {
    "module__input_size": [12],
    "module__neurons": [16, 32, 64],
    "max_epochs": [50, 100],
    "lr": [0.001, 0.0005]
}

grid = GridSearchCV(net, param_grid, cv=3, scoring='accuracy')
grid.fit(X_train.astype('float32'), y_train.astype('float32'))


ValueError: 
All the 36 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/skorch/classifier.py", line 170, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1334, in fit
    self.initialize()
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 920, in initialize
    self._initialize_module()
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 779, in _initialize_module
    self.initialize_module()
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 626, in initialize_module
    module = self.initialized_instance(self.module, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 603, in initialized_instance
    return instance_or_cls(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ChurnANN.__init__() got an unexpected keyword argument 'neurons'


In [89]:
from skorch import NeuralNetClassifier
import torch.nn as nn
import torch

class ChurnANN(nn.Module):
    def __init__(self, input_size=12, neurons=32):
        super().__init__()
        self.fc1 = nn.Linear(input_size, neurons)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(neurons, neurons//2)
        self.relu2 = nn.ReLU()
        self.output = nn.Linear(neurons//2, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu1(self.fc1(x))
        x = self.relu2(self.fc2(x))
        x = self.sigmoid(self.output(x))
        return x

net = NeuralNetClassifier(
    ChurnANN,
    optimizer=torch.optim.Adam,
    criterion=nn.BCELoss,
    max_epochs=10,
    batch_size=32,
)

param_grid = {
    "module__input_size": [12],
    "module__neurons": [16, 32, 64],
    "max_epochs": [50, 100],
    "lr": [0.001, 0.0005]
}

grid = GridSearchCV(net, param_grid, cv=3, scoring='accuracy')
grid.fit(X_train.astype("float32"), y_train.astype("float32"))


ValueError: 
All the 36 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/skorch/classifier.py", line 170, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1336, in fit
    self.partial_fit(X, y, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1295, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1207, in fit_loop
    self.run_single_epoch(iterator_train, training=True, prefix="train",
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1243, in run_single_epoch
    step = step_fn(batch, **fit_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1122, in train_step
    self._step_optimizer(step_fn)
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1077, in _step_optimizer
    optimizer.step(step_fn)
  File "/usr/local/lib/python3.12/dist-packages/torch/optim/optimizer.py", line 517, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/optim/optimizer.py", line 82, in _use_grad
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/optim/adam.py", line 226, in step
    loss = closure()
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1111, in step_fn
    step = self.train_step_single(batch, **fit_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1011, in train_step_single
    loss = self.get_loss(y_pred, yi, X=Xi, training=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/skorch/classifier.py", line 155, in get_loss
    return super().get_loss(y_pred, y_true, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/skorch/net.py", line 1696, in get_loss
    return self.criterion_(y_pred, y_true)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py", line 727, in forward
    return F.binary_cross_entropy(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/functional.py", line 3517, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])) is deprecated. Please ensure they have the same size.


In [ ]:

        # evaluate accuracy
        # update best score
